name: Build exe

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 使用するPythonバージョン

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build
      run: pyinstaller --onefile peak_picking_tool.py

    - name: List files in dist directory
      run: ls -al dist  # 確認のため、distフォルダの内容を表示

    - name: Upload exe
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/peak_picking_tool  # ファイル名が正しいか確認
